env:
    rcloneconfig: "ENCRYPTED[3f141fcf6edda367c3618021b8ffeef6683b19dee14e096ab0db284f71144e7bc3e2c6f10b601e5879306d01bbb38afd]"
    anu:
    lunch: lunch syberia_flashlmdd-userdebug
    make: mka
task:
  name: "Setting Up, Syncing, Building and Uploading..."
  timeout_in: 480m  
  container:
      image: inok2341/anu:latest
      cpu: 8
      memory: 32G
 
  Build-Env-Setup_background_script:
       - mkdir -p ~/.config/rclone
       - echo "$rcloneconfig" > ~/.rclone.conf
       - git config --global user.name "imannig"
       - git config --global user.email "akugedekntl@gmail.com"
       - rclone copy ping2109drive:cherish-v50/ccache.tar.gz ~/ -P
       - cd ~/
       - time tar xf ccache.tar.gz
       - cd ~/
 
  Storage-Checker_background_script:
      - df -h
      - lsblk
      - ls -l -a -h
      - ./w.sh

  Sync_script:
    #  - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Start Sync Source"
      - echo "============================"
      - echo "Syncing The Sources..."
      - echo "============================"
      - mkdir -p ~/rom
      - cd ~/rom
      - repo init -q --no-repo-verify --depth=1 -u https://github.com/syberia-project/manifest.git -b 12.1 -g default,-mips,-darwin,-notdefault
      - repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j 30 || repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j 8
      - git clone --depth=1 https://github.com/anht3889/android_device_lge_sm8150-common.git -b aosp device/lge/sm8150-common
      - git clone --depth=1 https://github.com/anht3889/android_device_lge_flash-common.git -b aosp device/lge/flash-common
      - git clone --depth=1 https://github.com/ping2109/android_device_lge_flashlmdd.git -b cherish device/lge/flashlmdd
      - git clone --depth=1 https://github.com/anht3889/android_device_lge_common.git -b aosp device/lge/common
      
      - git clone --depth=1 https://github.com/anht3889/proprietary_vendor_lge.git -b aosp vendor/lge
      - git clone --depth=1 https://github.com/anht3889/android_kernel_lge_sm8150_new.git -b aosp kernel/lge/sm8150
      - git clone --depth=1 https://github.com/anht3889/android_hardware_lge.git -b aosp hardware/lge
      
      - echo "============================"
      - echo "Sync Completed!"
      - echo "============================"
#      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Sync Completed!"

  Build_script:
      - echo "Lest start this fuck"
   #   - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Build Started!"
      - ./collect.sh
   #   - ./final.sh
    #  - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Build $(cd /tmp/rom/out/target/product/juice/ && ls Nusantara*.zip) Completed!"

  Upload_script:
#      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Uploading Build $(cd ~/rom/out/target/product/juice/ && ls Nusantara*.zip) To Your Drive"
  #    - rclone copy ~/rom/out/target/product/juice/exthm*.zip cirrus:juice -P
#      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Build $(cd /tmp/rom/out/target/product/juice/ && ls Nusantara*.zip) Uploaded Successfully!"
    #  - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Compres ccache"
      - ./ziping.sh
      - cd ~/
     # - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Uploading ccache...."
      - rclone copy ccache.tar.gz ping2109drive:cherish-v50 -P
      - echo " "
     # - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Uploadinig Ccahchhe Successyffully!"
