env:
    rcloneconfig: "ENCRYPTED[3f141fcf6edda367c3618021b8ffeef6683b19dee14e096ab0db284f71144e7bc3e2c6f10b601e5879306d01bbb38afd]"
    anu:
    lunch: lunch lineage_j6lte-userdebug
    make: mka
task:
  name: "Setting Up, Syncing, Building and Uploading..."
  timeout_in: 480m  
  container:
      image: inok2341/anu:latest
      cpu: 8
      memory: 32G
 
  Build-Env-Setup_background_script:
       - mkdir -p ~/.config/rclone
       - echo "$rcloneconfig" > ~/.rclone.conf
       - git config --global user.name "imannig"
       - git config --global user.email "akugedekntl@gmail.com"
       - rclone copy ping2109drive:los-j6-q/ccache.tar.gz ~/ -P
       - cd ~/
       - time tar xf ccache.tar.gz
       - cd ~/
 
  Storage-Checker_background_script:
      - df -h
      - lsblk
      - ls -l -a -h
      - ./w.sh

  Sync_script:
    #  - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Start Sync Source"
      - echo "============================"
      - echo "Syncing The Sources..."
      - echo "============================"
      - mkdir -p ~/rom
      - cd ~/rom
      - repo init --depth=1 -u https://github.com/LineageOS/android.git -b lineage-18.1
      - repo sync --no-repo-verify -c --force-sync --no-clone-bundle --no-tags --optimized-fetch --prune -j`nproc`
      - git clone https://github.com/samsungexynos7870/android_device_samsung_universal7870-common.git -b lineage-18.1 device/samsung/universal7870-common
      - git clone https://github.com/samsungexynos7870/android_device_samsung_j6lte.git -b lineage-18.1 device/samsung/j6lte
      - git clone https://github.com/samsungexynos7870/android_kernel_samsung_exynos7870.git -b aosp-11 kernel/samsung/exynos7870
      - git clone https://github.com/samsungexynos7870/android_vendor_samsung_universal7870-common.git -b lineage-18.1 vendor/samsung/universal7870-common
      - git clone https://github.com/samsungexynos7870/android_vendor_samsung_j6lte.git -b common vendor/samsung/j6lte
      - git clone https://github.com/samsungexynos7870/android_hardware_samsung.git -b lineage-18.1 hardware/samsung
      
      - git clone https://github.com/TALUAtGitHub/android_hardware_samsung_slsi_exynos.git -b lineage-18.1 hardware/samsung_slsi/exynos
      - git clone https://github.com/TALUAtGitHub/android_hardware_samsung_slsi_exynos5.git -b lineage-18.1 hardware/samsung_slsi/exynos5
      - git clone https://github.com/TALUAtGitHub/android_hardware_samsung_slsi_exynos7870.git -b lineage-18.1 hardware/samsung_slsi/exynos7870
      
      - echo "============================"
      - echo "Sync Completed!"
      - echo "============================"
#      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Sync Completed!"

  Build_script:
      - echo "Lest start this fuck"
   #   - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Build Started!"
      - ./collect.sh
   #   - ./final.sh
    #  - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Build $(cd /tmp/rom/out/target/product/juice/ && ls Nusantara*.zip) Completed!"

  Upload_script:
#      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Uploading Build $(cd ~/rom/out/target/product/juice/ && ls Nusantara*.zip) To Your Drive"
  #    - rclone copy ~/rom/out/target/product/juice/exthm*.zip cirrus:juice -P
#      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Build $(cd /tmp/rom/out/target/product/juice/ && ls Nusantara*.zip) Uploaded Successfully!"
    #  - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Compres ccache"
      - ./ziping.sh
      - cd ~/
     # - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Uploading ccache...."
      - rclone copy ccache.tar.gz ping2109drive:los-j6-q -P
      - echo " "
     # - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Uploadinig Ccahchhe Successyffully!"
